package com.browser.core_browser.domain.model

import android.webkit.WebView
import java.util.UUID

/**
 * Represents a single tab in the RedBrowser.
 *
 * Each tab is uniquely identified by its [id], contains a [webView] to render web content,
 * and holds the current [url] being displayed.
 *
 * @property id Unique identifier for the tab. A new UUID is generated by default when a tab is created.
 * @property webView The WebView instance responsible for loading and displaying web content in this tab.
 * @property url The current URL loaded in the WebView. Can be updated as the user navigates.
 */
data class RedBrowserTab(
    val id: UUID = UUID.randomUUID(),
    val webView: WebView,
    var url: String
)
